version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgrespw@db/postgres
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt:ro
      - /etc/letsencrypt/live/:/data/letsencrypt/
    command: /bin/sh -c "env && while :; do sleep 6h & wait $${!}; nginx -s reload; certbot renew; done & nginx -g 'daemon off;'"
    certbot:
      image: certbot/certbot
      volumes:
        - ./certs:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"